name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        # Add repositories if needed for minisign
        sudo apt-get update
        # Install minisign
        sudo apt-get install -y minisign
        # Install BLAKE3 CLI tool (b3sum)
        cargo install b3sum || echo "Using existing b3sum installation"
        # Make sure b3sum is in PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Install dependencies
      run: |
        poetry install --with dev
    
    - name: Lint with flake8
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        poetry run pytest